### ISSUE TITLE
Advanced extension: Typography Field live update. 

### ISSUE THREAD

**Issue by benjaminritner** [reduxframework/customizer-integration#2]
Hey,
 The Typography Field doesn't live update on the site when you change the font family. If you change the font then the color it will update but it won't update when you change just the font family. Funny thing is if you change the font family a second time it will then show you the font family you tried to view the first time. 

This is again only on the site preview. The little preview box in the panel works fine.

Ben

**Comment by dovy** [comment]
Just did a push to the ReduxCore. Do a pull and that should fix it.

**Comment by benjaminritner** [comment]
Hey,
 This is still not working for me. Not working on your demo either if you want to look at it: http://demo.redux.io/wp-admin/customize.php

Just go to typography > h2 and change just the font family. No change will happen on the site. then change the color or something and you will see the font family change.

Ben
